--
name: "Github Actions Workflow Demo"
on:
  push:
    branches:
      - master
      - main

jobs:
  image-building:
    runs-on: ubuntu-latest

    steps:

      - name: "Current Date"
        run: date


      - name: "OS details"
        run: cat /etc/os-release

      - name: "Memory Details"
        run: free -m

      - name: "Current Working directories and contents"
        run: |
          pwd
          ls -al

      - name: "Packer Installation"
        run: |
          wget https://releases.hashicorp.com/packer/1.14.2/packer_1.14.2_linux_amd64.zip
          unzip packer_1.14.2_linux_amd64.zip
          pwd
          ls -al

